travis:
  secure:
    BINSTAR_TOKEN: ituxjSXFvGxGNf92y1FpEZkL3suZ1tOA06UtSwKF6mgfUZ+fu6BPSy3oaN4fgbIrxjSFIIY8jOUL0W9AQLQYMMx3Llz7DFeJbQ8lv64lcClPl2b1eMktogs7RpIn1jFJ73iFng37Pe4px6cz7Y9Y04AsLm7QIJP+M9isVte2xd1A0jO18iibC9ztPpGf64PtXi65UrOPFX7Kkj8uPcDzLIqB7CIYHo4NWwbpkOacsJyi7CBnxXO3/pEsflfJ42AqAznjawYdcMPgK25MGIjhQ9XCzhYWgJWVhhZbKOUOD7AfV5k9n/hHahk34B2cj0WWAdq6zADW6d0DsajeObbxNxDYVmkFEYx3Gs6ffpvAFYkQL9y9zF0hqu9BaTdUHppG2ymd9QhMaKQKFKkIbduhPKXz2PiXFaes82gdgMGiJlpW++z4nPdiDb9C/o4ubVrL82RnewilNL83gXpwzc8sw+MNLBrPJjdJxvqnhonk1AeExPRA1ymVTddAyv/aAIIAS/2MhNhXnCLy/s/Gi/9BEfik8OCLtLypkWKDX9siJiOVgpXe9aEvCnfTNw1ilRXBt7lbZcOtuGq4FegtbE8/+ONv5NzCAfgpE1JeFU9m7eHRkc8S8T4QRPUCt0gyQo6rSTCvg9Ki9n8NrUawk0q2RgkwTqlVGwYPweftuQponrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
